name: Splatoon 3 Bankara Notifier      # ← タイトルも合わせて変更可

on:
  schedule:
    - cron: '5 7 * * *'          
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      SHEET_ID:                   ${{ secrets.SHEET_ID }}          # ← シート ID
      SHEET_GID:                  ${{ secrets.SHEET_GID }}         # ← シート GID
      LINE_USER_IDS:            ${{ secrets.LINE_USER_IDS }}   # ← plural
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier
        run: python spla3_notifier.py
